-- =========================================================
-- 99. DROP ALL TABLES / SEQUENCES
-- Oracle
-- Run only when database reset is needed.
-- =========================================================

-- TABLE DROP
-- CASCADE CONSTRAINTS 구문만 유지합니다.

DROP TABLE compensation_payment_doc CASCADE CONSTRAINTS;
DROP TABLE compensation_calc_doc CASCADE CONSTRAINTS;
DROP TABLE compensation_claim_doc CASCADE CONSTRAINTS;
DROP TABLE damage_action_doc CASCADE CONSTRAINTS;
DROP TABLE invest_doc CASCADE CONSTRAINTS;
DROP TABLE app_doc CASCADE CONSTRAINTS;
DROP TABLE compensation_payment CASCADE CONSTRAINTS;
DROP TABLE compensation_calc CASCADE CONSTRAINTS;
DROP TABLE compensation_claim CASCADE CONSTRAINTS;
DROP TABLE damage_action CASCADE CONSTRAINTS;
DROP TABLE damage_site_invest CASCADE CONSTRAINTS;
DROP TABLE agriculture_damage_app CASCADE CONSTRAINTS;
DROP TABLE quality_assurance_officer CASCADE CONSTRAINTS;
DROP TABLE applicant CASCADE CONSTRAINTS;

-- SEQUENCE DROP
-- 03_create_sequences.sql에서 생성한 시퀀스와 동일한 목록입니다.

DROP SEQUENCE SEQ_COMPENSATION_CLAIM_DOC;
DROP SEQUENCE SEQ_DAMAGE_ACTION;
DROP SEQUENCE SEQ_COMPENSATION_CALC_DOC;
DROP SEQUENCE SEQ_COMPENSATION_PAYMENT;
DROP SEQUENCE SEQ_INVEST_DOC;
DROP SEQUENCE SEQ_COMPENSATION_CLAIM;
DROP SEQUENCE SEQ_DAMAGE_ACTION_DOC;
DROP SEQUENCE SEQ_COMPENSATION_PAYMENT_DOC;
DROP SEQUENCE SEQ_QUALITY_ASSURANCE_OFFICER;
DROP SEQUENCE SEQ_APP_DOC;
DROP SEQUENCE SEQ_APPLICANT;
DROP SEQUENCE SEQ_DAMAGE_SITE_INVEST;
DROP SEQUENCE SEQ_COMPENSATION_CALC;


